version: "3"
services:
  mysql57:
    platform: linux/x86_64
    build: ./mysql_57/
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    ports:
      - "4306:3306"
